### ISSUE TITLE
C'est quoi le but ?

### ISSUE THREAD

**Issue by cmarchand** [FredericLanic/ladybug#9]
Pour moi qui n'ai jamais joué à PacMan, c'est quoi le but du jeu ? Et surtout, quand est-ce que c'est finit ?

Des fois, les fantômes ont une autre tête ; ça veut dire quoi ?

Une page avec ces infos serait bien.

Ensuite, l'affichage de l'aide seulement quand F1 est enfoncé n'est pas très pratique. Un mode on/off serait plus facile je pense...

**Comment by FredericLanic** [comment]
Merci Christophe,
Je vais tenter de répondre dès que possible à tes questions.
Ça marche
